<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Windows_Listener_Worker-89c97de2-00ea-424b-8edc-d76ec0cf7d01</UserSecretsId>

	  <PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>true</SelfContained>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.7" />
  </ItemGroup>
</Project>



